import 'package:cloud_firestore/cloud_firestore.dart';

/// TreatmentPlan model
/// Relationships:
///   - Consultation (1) generates (1) TreatmentPlan
class TreatmentPlan {
  final String treatmentPlanID;
  final String medicationName;
  final String dosage;
  final String duration;
  final double frequency;
  final DateTime lastUpdated;
  final String consultationID; // FK to Consultation (generated by)

  TreatmentPlan({
    required this.treatmentPlanID,
    required this.medicationName,
    required this.dosage,
    required this.duration,
    required this.frequency,
    required this.lastUpdated,
    required this.consultationID,
  });

  // ── Firestore serialization ──

  /// Create a TreatmentPlan from a Firestore document map.
  factory TreatmentPlan.fromMap(Map<String, dynamic> map, {String? id}) {
    return TreatmentPlan(
      treatmentPlanID: id ?? map['treatmentPlanID'] as String,
      medicationName: map['medicationName'] as String? ?? '',
      dosage: map['dosage'] as String? ?? '',
      duration: map['duration'] as String? ?? '',
      frequency: (map['frequency'] as num?)?.toDouble() ?? 0.0,
      lastUpdated: (map['lastUpdated'] as Timestamp).toDate(),
      consultationID: map['consultationID'] as String? ?? '',
    );
  }

  /// Convert the TreatmentPlan to a Map for Firestore storage.
  Map<String, dynamic> toMap() {
    return {
      'treatmentPlanID': treatmentPlanID,
      'medicationName': medicationName,
      'dosage': dosage,
      'duration': duration,
      'frequency': frequency,
      'lastUpdated': Timestamp.fromDate(lastUpdated),
      'consultationID': consultationID,
    };
  }

  /// Convenience factory from a Firestore DocumentSnapshot.
  factory TreatmentPlan.fromDocument(DocumentSnapshot doc) {
    return TreatmentPlan.fromMap(
      doc.data() as Map<String, dynamic>,
      id: doc.id,
    );
  }

  // ── Methods from UML ──

  /// Add medication details to the plan.
  TreatmentPlan addMedication({
    required String medicationName,
    required String dosage,
    required String duration,
    required double frequency,
  }) {
    return copyWith(
      medicationName: medicationName,
      dosage: dosage,
      duration: duration,
      frequency: frequency,
      lastUpdated: DateTime.now(),
    );
  }

  /// Update the plan with new values.
  TreatmentPlan updatePlan({
    String? medicationName,
    String? dosage,
    String? duration,
    double? frequency,
  }) {
    return copyWith(
      medicationName: medicationName,
      dosage: dosage,
      duration: duration,
      frequency: frequency,
      lastUpdated: DateTime.now(),
    );
  }

  /// Get a text summary of the plan.
  String getPlanSummary() {
    return 'Medication: $medicationName, Dosage: $dosage, '
        'Duration: $duration, Frequency: $frequency';
  }

  @override
  String toString() {
    return 'TreatmentPlan(treatmentPlanID: $treatmentPlanID, '
        'medicationName: $medicationName, dosage: $dosage, '
        'duration: $duration, frequency: $frequency, '
        'lastUpdated: $lastUpdated, consultationID: $consultationID)';
  }

  /// Creates a copy with the given fields replaced.
  TreatmentPlan copyWith({
    String? treatmentPlanID,
    String? medicationName,
    String? dosage,
    String? duration,
    double? frequency,
    DateTime? lastUpdated,
    String? consultationID,
  }) {
    return TreatmentPlan(
      treatmentPlanID: treatmentPlanID ?? this.treatmentPlanID,
      medicationName: medicationName ?? this.medicationName,
      dosage: dosage ?? this.dosage,
      duration: duration ?? this.duration,
      frequency: frequency ?? this.frequency,
      lastUpdated: lastUpdated ?? this.lastUpdated,
      consultationID: consultationID ?? this.consultationID,
    );
  }
}
