// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1QvKr-K02iUUUvNocjG8FNtQ3qd9__a0',
    appId: '1:702053481596:android:244de0dcb6300ebce9ddf9',
    messagingSenderId: '702053481596',
    projectId: 'khotaa-app',
    databaseURL: 'https://khotaa-app-default-rtdb.firebaseio.com',
    storageBucket: 'khotaa-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANogRvU6eROMfsXM5ruXPqJl7ZD9r6UY4',
    appId: '1:702053481596:ios:3f17311d2b496e50e9ddf9',
    messagingSenderId: '702053481596',
    projectId: 'khotaa-app',
    databaseURL: 'https://khotaa-app-default-rtdb.firebaseio.com',
    storageBucket: 'khotaa-app.firebasestorage.app',
    iosBundleId: 'com.khotaa.app.khotaaApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAryw4m7MK5lYD5Xa9_ZzBYjCt5NGLqINs',
    appId: '1:702053481596:web:61d7d01ab6b4dbeee9ddf9',
    messagingSenderId: '702053481596',
    projectId: 'khotaa-app',
    authDomain: 'khotaa-app.firebaseapp.com',
    databaseURL: 'https://khotaa-app-default-rtdb.firebaseio.com',
    storageBucket: 'khotaa-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANogRvU6eROMfsXM5ruXPqJl7ZD9r6UY4',
    appId: '1:702053481596:ios:3f17311d2b496e50e9ddf9',
    messagingSenderId: '702053481596',
    projectId: 'khotaa-app',
    databaseURL: 'https://khotaa-app-default-rtdb.firebaseio.com',
    storageBucket: 'khotaa-app.firebasestorage.app',
    iosBundleId: 'com.khotaa.app.khotaaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAryw4m7MK5lYD5Xa9_ZzBYjCt5NGLqINs',
    appId: '1:702053481596:web:e54e5735835504a1e9ddf9',
    messagingSenderId: '702053481596',
    projectId: 'khotaa-app',
    authDomain: 'khotaa-app.firebaseapp.com',
    databaseURL: 'https://khotaa-app-default-rtdb.firebaseio.com',
    storageBucket: 'khotaa-app.firebasestorage.app',
  );
}
